apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-14T11:10:57Z"
  labels:
    color: blue
    run: nginx
  name: nginx
  namespace: user-28
  resourceVersion: "2933880"
  selfLink: /api/v1/namespaces/user-28/pods/nginx
  uid: 7131c6d6-2bd9-4d6e-bffe-fe673418772b
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    env:
    - name: "DUMMY_DATABASE_PASSWORD"
      value: "admin"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html/
    livenessProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 3
      periodSeconds: 3
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 3
      periodSeconds: 3
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
  - image: busybox:latest
    name: busybox
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true: do echo 'DUMMY_DATABASE_PASSWORD='$DUMMY_DATABASE_PASSWORD >> /html/index.html && sleep 5; done;" ]
    volumeMounts:
    - name: htmldir
      mountPath: /html
    env:
    - name: "DUMMY_DATABASE_PASSWORD"
      value: "admin"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-sx11
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: htmldir
    emptyDir: {}
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T11:10:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T11:10:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T11:10:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T11:10:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9aa50ef436686a90ad8c09320a95c3aaea1aefce1832f93a29bfc9ab51b6582c
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-14T11:10:59Z"
  hostIP: 10.170.15.202
  phase: Running
  podIP: 10.60.7.19
  podIPs:
  - ip: 10.60.7.19
  qosClass: BestEffort
  startTime: "2021-01-14T11:10:57Z"
