apiVersion: v1
data:
  fluent.conf: |-
    <source>
      type tail
      path /logs/**/access.log
      tag nginx.access
      format nginx
    </source>

    <source>
      @type tail
      format /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$/
      tag nginx.error
      path /logs/**/error.log
    </source>

    <match nginx.access>
      @type stdout
    </match>

    <match nginx.error>
      @type stdout
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-19T02:02:00Z"
  name: fluent-conf
  namespace: user-28
  resourceVersion: "5208169"
  selfLink: /api/v1/namespaces/user-28/configmaps/fluent-conf
  uid: a678c117-2bae-4208-b166-28fc0a0a9ea0
